apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: nginx
    image: docker.io/nginx:1.14.2
  - name: mysql
    image: docker.io/mysql
    env:
     - name: MYSQL_ROOT_PASSWORD
       value: password 


