apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    name: db-tier
spec:
  containers:
  - name: postgres
    image: postgres
    env:
    - name: POSTGRES_PASSWORD
      value: mysecretpassword

