apiVersion: v1
kind: Pod
metadata:
  name: mypod 
  labels:
     app:  myfirst-pod
     type: front-end
spec:
  containers:
    - name: nginx-container
      image: quay.io/gauravkumar9130/nginxdemo 
