apiVersion: v1
kind: ReplicationController
metadata:
 name: rc-web
spec:
 replicas: 2
 template:
  metadata:
   labels:
    app: web
  spec: 
   containers:
    - name: r1c
      image: quay.io/gauravkumar9130/mywebapp
